### PR TITLE
updating people

### PR DESCRIPTION
**Pull request by TimOlesnavage**

### CODE REVIEW

**Comment by drdelux** [comment]
Hello Jordan Had personal items to deal with last night. After consideration of my lack of computer skills and trying to learn a new operating system (MAC) in the middle of trying to learn the class work, I find myself steadily falling further behind.

I don't mind staying up late reading or getting up at 4:30 to read more but I'm going to have to learn the MAC before I try to use it for this class. I hope you folks will extend me the opportunity to try this again in the near future?

Will stop by "Elevate Blue" today or tomorrow and make sure I don't owe you folks any money. Thank you for your concern, you're a good teacher, hope I get another chance to do this course.

Many Thanks

Greg Smith



________________________________

**Comment by Zenprechaun** [comment]
Hi Greg, if all you need is a computer to use, I think I have an extra one. If you want I could help you catch up too. You should stick with it, it’s only a few more weeks. Give me a call.

 

Thank you and Cheers,

Mike McDermott, CEO

310-956-2936

 

CONFIDENTIAL NOTICE: All information, data and attachments contained in this message are confidential and are the property of GIVFTiT, Inc. If you are not the intended recipient and have received this email in error delete it immediately and destroy all copies. Any redistribution, communication or actions taken on information contained in this message is strictly prohibited.

**Comment by drdelux** [comment]
Hello Mike Sorry it's taken so long to get back to you Two local contractors called me and asked me to fix things for them that they don't know how to do. At 67 I'm out of shape and an eight hour day often leaves me at home eating pain pills at night.

I really wanted to succeed in that class but, as u  noted my computer skills are non existent. Going to the Apple store in Reno for a class tomorrow night! Hope they can unlock whatever it is I've done to my new Mac!. Thank u so much for your concern and help. Soon as I learn this platform I'll give it another try. Again, thank you. Greg Smith


________________________________

**Comment by jordanpapaleo** [comment]
Hi Greg - 

You are sending these messages to the entire class by communicating though github.  Github is intended for course specific communications only.

Please use email for personal correspondences. [Class Emails Addresses](https://github.com/CodeTahoe/CT100/blob/master/everyone.md)

Thanks, 

Jordan

**Pull request closed without merging**
